### PR TITLE
fix garbage cycles

### PR DESCRIPTION
**Pull request by kostamax27**

### CODE REVIEW

**Comment by IvanCraft623** [comment]
Thanks for your contribution! Could you check if there are any cycle missing at the latest commit?

**Comment by kostamax27** [comment]
> Thanks for your contribution! Could you check if there are any cycle missing at the latest commit?

garbage cycles remained

```log
gc
Command output | ---- Garbage collection result ----
Command output | Chunks: 43
Command output | Entities: 0
Command output | Cycles: 93
Command output | Memory freed: 5.45 MB
```

**Comment by IvanCraft623** [comment]
> garbage cycles remained

I mean if there are new cycles

**Comment by kostamax27** [comment]
> > garbage cycles remained
> 
> I mean if there are new cycles, async pathfinding + your changes

yeah there no more cycles left

**Review by IvanCraft623 — APPROVED** [review]
All right, thanks for your contribution!

**Pull request merged**
